# Cockatoo dark theme
[colors.bright]
black = "0xe5e5eb"
blue = "0x708296"
cyan = "0x79ada7"
green = "0xa4bd84"
magenta = "0xcaafeb"
red = "0xe87c69"
white = "0x8f9fbc"
yellow = "0xe6bb86"

[colors.cursor]
cursor = "0xffffff"

[colors.normal]
black = "0x2f353e"
blue = "0x708296"
cyan = "0x79ada7"
green = "0xa4bd84"
magenta = "0xcaafeb"
red = "0xe87c69"
white = "0xe5e5eb"
yellow = "0xe6bb86"

[colors.primary]
background = "0x2f353e"
foreground = "0xbebec3"
